### ISSUE TITLE
"TODO: fix the bug of original Stochatic depth" ?

### ISSUE THREAD

**Issue by ddkang** [felixgwu/img_classification_pk_pytorch#3]
What is the bug in the original stochastic depth?

**Comment by taineleau-zz** [comment]
@ddkang I feel I have already fixed that.  see [4e8ddfb](https://github.com/felixgwu/img_classification_pk_pytorch/commit/c72f4c225328f0b212f5682869a2eb338fa7d123)

**Comment by Shiweiliuiiiiiii** [comment]
@taineleau-zz Hi, thank you for your efficient implementation. Can you explain why the original stochastic depth would cause a bug? Thank you.
