### ISSUE TITLE
How can I use this project with python 2.7

### ISSUE THREAD

**Issue by yuhuixu1993** [felixgwu/img_classification_pk_pytorch#6]
My python version is 2.7 and when I run this command"CUDA_VISIBLE_DEVICES=0 python main.py --data cifar10+ --arch resnet --depth 56 --save save/cifar10+-resnet-56 --epochs 164", this error comes out"IndentationError: unexpected indent". It seems the problem of  the python version. How can I solve this problem since you mentioned your project suits for 2,7. Many Thanks!

**Comment by taineleau-zz** [comment]
I don't think it's because of the Python version. IndentationError means you might use spaces or tab for indent at the same time within a project. Please check the indent first. Did you modify the code base?

**Comment by taineleau-zz** [comment]
And I would recommend you use PyTorch 3.x instead if the error still comes up.

**Comment by yuhuixu1993** [comment]
Thank you so much, I've solved my problem! I change the print lines in the utils.py.
